### ISSUE TITLE
Carry link embeds with quote

### ISSUE THREAD

**Issue by MulverineX** [Juby210/message-link-embed#1]
![image](https://user-images.githubusercontent.com/12068027/82946307-58dde980-9f5b-11ea-904d-fe90df8d59f6.png)
![image](https://user-images.githubusercontent.com/12068027/82946311-5b404380-9f5b-11ea-96b9-f3e6ea6531d0.png)

**Comment by Juby210** [comment]
do you mean rendering videos from link, yeah?
